# Generated by Django 6.0.6 on 2026-06-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
