# Generated by Django 6.0.6 on 2026-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_booked_at_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True
            ),
        ),

        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(
                default='Paid',
                max_length=20
            ),
        ),
    ]