# Generated by Django 6.0.6 on 2026-06-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
